name: deploy frontend
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: [self-hosted, frontend]
    steps:
      - name: atualizar código
        run: |
          cd ~/p2-sam-frontend
          git pull origin main
          pnpm install
          export NODE_OPTIONS="--max-old-space-size=4096"
          pnpm build
          pm2 restart frontend
